#pragma once

const int CLASS_ADVENTURER = 35;
const int CLASS_SWORDSMAN = 36;
const int CLASS_ARCHER = 37;
const int CLASS_MAGICIAN = 38;
const int CLASS_MARTIAL_ARTIST = 39;
const int LOBBY_DELETION_WRONG_USERNAME = 360;
const int LOBBY_CREATION_PSEUDO_TAKEN = 875;
const int FAMILY_ROLE_HEAD = 915;
const int FAMILY_ROLE_DEPUTEE = 916;
const int FAMILY_ROLE_GUARDIAN = 917;
const int FAMILY_ROLE_MEMBER = 918;
const int LOBBY_ALREADY_HAVE_MARTIAL_ARTIST = 2361;
